### ISSUE TITLE
Input yaml specs

### ISSUE THREAD

**Issue by sunqm** [pyscf/pyscfcli#1]
Please feel free to post your comments.

In the current implementation
* Keys are just pyscf classes and attributes.
* Input order matters. Mole/Cell needs to be specified first, then HF/post-HF/DFT methods, then solvent model, then geomopt
```
Mole:  # or Cell
  verbose: 4
  atom: |
    H 0 0 0
    H 0 0 1
  basis:
    name-string-or-anything-supported-by-basis-input
HF:  # or any method keywords, like, KS, CCSD, MP2, CASSCF(x,x), DFT ..
  conv_tol: 1e-9
  level_shift: 0.2
  max_cycle: 12
  xc:
    b3lyp
  grids:
    level: 3
  density_fit:
    auxbasis: weigend
  newton:
    micro: 2
  x2c:
    atom
  results: # a list of attributes in results, if key-value are provided, the
           # key will be used as function name, values are used as arguments
           # (or kwargs)
    - mo_energy
    - e_tot
Solvent:  # or the name of Solvent-model (ddCOSMO, ddPCM), default is ddCOSMO
  eps: 1.8
CCSD:  # or any post-HF method names
  results:
    - e_tot
    - e_corr
Gradients:  # or other property names
  unit: au
Geomopt:
```
